dist: trusty
sudo: require
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

compiler:
  - gcc
before_install:
  - pip install --user cpp-coveralls
script:
  - cmake -DCOVERAGE=1 .
  - cmake --build .
  - ./erkir_test
after_success:
  - coveralls --verbose --exclude test
