dist: trusty
sudo: require
language: cpp
compiler:
  - gcc
before_install:
  - pip install --user cpp-coveralls
script:
    - g++ -std=c++11 -coverage -Isrc -Iinclude test/test.cpp -o test_app
    - ./test_app
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - coveralls --verbose --exclude test

